### ISSUE TITLE
Release upgrade dependency version for ion-js 5.2.0

### ISSUE THREAD

**Issue by GanyuanTan** [amazon-ion/ion-hash-js#61]
Hi team, is there any plan to use the latest version of `ion-js`? Currently [Qldb driver](https://github.com/awslabs/amazon-qldb-driver-nodejs) depends on the `ion-hash-js` library, which has the old version 4.3.0 of `ion-js` as peer dependency. We got the following error when we did the upgrade:

```
npm ERR! While resolving: ion-hash-js@2.0.0
npm ERR! Found: ion-js@5.2.0
npm ERR! node_modules/ion-js
npm ERR!   dev ion-js@"^5.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer ion-js@"^4.0.0" from ion-hash-js@2.0.0
npm ERR! node_modules/ion-hash-js
npm ERR!   ion-hash-js@"^2.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: ion-js@4.3.0
npm ERR! node_modules/ion-js
npm ERR!   peer ion-js@"^4.0.0" from ion-hash-js@2.0.0
npm ERR!   node_modules/ion-hash-js
npm ERR!     ion-hash-js@"^2.0.0" from the root project
```

We have a [customer](https://github.com/awslabs/amazon-qldb-driver-nodejs/issues/428) requires the version upgrade and we would love to know the plan for the release of `ion-hash-js` with the latest [`ion-js` version](https://github.com/amazon-ion/ion-js)

**Comment by zslayton** [comment]
Hi, sorry for the delayed reply. We'll take a look at this and see if we can prioritize it.

**Comment by linlin-s** [comment]
Hello, our team is currently working on upgrading the JS version to 5.2.0, and further investigation is needed to resolve the build failure.

**Comment by linlin-s** [comment]
The latest release[ v2.1.0](https://github.com/amazon-ion/ion-hash-js/releases/tag/v2.1.0) fixed this issue.
